//
//  country.swift
//  RMT
//
//  Created by vt9 on 2023/8/5.
//
//https://ws.mofa.gov.tw/Download.ashx?u=LzAwMS9VcGxvYWQvT2xkRmlsZS9SZWxGaWxlLzI3MDAvMTY5NDQwLzBjNzAxN2NlLWNlMzAtNDhhMi1iOGY0LTc3ODY5ZjcxZDk4NC5wZGY%3D&n=5aSW5Lqk6YOo5ZCE5ZyL5Lit6Iux5paH5ZCN56ix5bCN54Wn6KGoXzEwODA4MjkucGRm

import Foundation

struct country {
    let CurrencyCode: String //國家代碼
    let CountryTwName: String //國家名稱tw
    let CountryEnName: String //國家名稱en
}

let countryInfo = [
    //country( CurrencyCode: "", CountryTwName: "請選擇", CountryEnName: " plz select one " ),
    country( CurrencyCode: "AED", CountryTwName: "阿拉伯聯合大公國", CountryEnName: "United Arab Emirates" ),
    country( CurrencyCode: "AFN", CountryTwName: "阿富汗", CountryEnName: "Afghanistan" ),
    country( CurrencyCode: "ALL", CountryTwName: "阿爾巴尼亞", CountryEnName: "Albania" ),
    country( CurrencyCode: "AMD", CountryTwName: "亞美尼亞", CountryEnName: "Armenia" ),
    country( CurrencyCode: "ANG", CountryTwName: "荷蘭", CountryEnName: "Netherlands Antilles" ),
    country( CurrencyCode: "AOA", CountryTwName: "安哥拉", CountryEnName: "Angola" ),
    country( CurrencyCode: "ARS", CountryTwName: "阿根廷", CountryEnName: "Argentina" ),
    country( CurrencyCode: "AUD", CountryTwName: "澳大利亞", CountryEnName: "Australia" ),
    country( CurrencyCode: "AWG", CountryTwName: "阿魯巴", CountryEnName: "Aruba" ),
    country( CurrencyCode: "AZN", CountryTwName: "亞塞拜然", CountryEnName: "Azerbaijan" ),
    country( CurrencyCode: "BAM", CountryTwName: "波士尼亞", CountryEnName: "Bosnia and Herzegovina" ),
    country( CurrencyCode: "BBD", CountryTwName: "巴貝多", CountryEnName: "Barbados" ),
    country( CurrencyCode: "BDT", CountryTwName: "孟加拉", CountryEnName: "Bangladesh" ),
    country( CurrencyCode: "BGN", CountryTwName: "保加利亞", CountryEnName: "Bulgaria" ),
    country( CurrencyCode: "BHD", CountryTwName: "巴林", CountryEnName: "Bahrain" ),
    country( CurrencyCode: "BIF", CountryTwName: "蒲隆地", CountryEnName: "Burundi" ),
    country( CurrencyCode: "BMD", CountryTwName: "百慕達", CountryEnName: "Bermuda" ),
    country( CurrencyCode: "BND", CountryTwName: "汶萊", CountryEnName: "Brunei" ),
    country( CurrencyCode: "BOB", CountryTwName: "玻利維亞", CountryEnName: "Bolivia" ),
    country( CurrencyCode: "BRL", CountryTwName: "巴西", CountryEnName: "Brazil" ),
    country( CurrencyCode: "BSD", CountryTwName: "巴哈馬", CountryEnName: "Bahamas" ),
    country( CurrencyCode: "BTN", CountryTwName: "不丹", CountryEnName: "Bhutan" ),
    country( CurrencyCode: "BWP", CountryTwName: "波札那", CountryEnName: "Botswana" ),
    country( CurrencyCode: "BYN", CountryTwName: "白俄羅斯", CountryEnName: "Belarus" ),
    country( CurrencyCode: "BZD", CountryTwName: "貝里斯", CountryEnName: "Belize" ),
    country( CurrencyCode: "CAD", CountryTwName: "加拿大", CountryEnName: "Canada" ),
    country( CurrencyCode: "CDF", CountryTwName: "民主剛果", CountryEnName: "Democratic Republic of the Congo" ),
    country( CurrencyCode: "CHF", CountryTwName: "瑞士", CountryEnName: "Switzerland" ),
    country( CurrencyCode: "CLP", CountryTwName: "智利", CountryEnName: "Chile" ),
    country( CurrencyCode: "CNY", CountryTwName: "中國", CountryEnName: "China" ),
    country( CurrencyCode: "COP", CountryTwName: "哥倫比亞", CountryEnName: "Colombia" ),
    country( CurrencyCode: "CRC", CountryTwName: "哥斯大黎加", CountryEnName: "Costa Rica" ),
    country( CurrencyCode: "CUP", CountryTwName: "古巴", CountryEnName: "Cuba" ),
    country( CurrencyCode: "CVE", CountryTwName: "維德角", CountryEnName: "Cape Verde" ),
    country( CurrencyCode: "CZK", CountryTwName: "捷克", CountryEnName: "Czech Republic" ),
    country( CurrencyCode: "DJF", CountryTwName: "吉布地", CountryEnName: "Djibouti" ),
    country( CurrencyCode: "DKK", CountryTwName: "丹麥", CountryEnName: "Denmark" ),
    country( CurrencyCode: "DOP", CountryTwName: "多明尼加", CountryEnName: "Dominican Republic" ),
    country( CurrencyCode: "DZD", CountryTwName: "阿爾及利亞", CountryEnName: "Algeria" ),
    country( CurrencyCode: "EGP", CountryTwName: "埃及", CountryEnName: "Egypt" ),
    country( CurrencyCode: "ERN", CountryTwName: "厄利垂亞", CountryEnName: "Eritrea" ),
    country( CurrencyCode: "ETB", CountryTwName: "衣索比亞", CountryEnName: "Ethiopia" ),
    country( CurrencyCode: "EUR", CountryTwName: "歐盟", CountryEnName: "European Union" ),
    country( CurrencyCode: "FJD", CountryTwName: "斐濟", CountryEnName: "Fiji" ),
    country( CurrencyCode: "FKP", CountryTwName: "福克蘭群島", CountryEnName: "Falkland Islands" ),
    country( CurrencyCode: "FOK", CountryTwName: "法羅群島", CountryEnName: "Faroe Islands" ),
    country( CurrencyCode: "GBP", CountryTwName: "英國", CountryEnName: "United Kingdom" ),
    country( CurrencyCode: "GEL", CountryTwName: "喬治亞", CountryEnName: "Georgia" ),
    country( CurrencyCode: "GGP", CountryTwName: "根西", CountryEnName: "Guernsey" ),
    country( CurrencyCode: "GHS", CountryTwName: "迦納", CountryEnName: "Ghana" ),
    country( CurrencyCode: "GIP", CountryTwName: "直布羅陀", CountryEnName: "Gibraltar" ),
    country( CurrencyCode: "GMD", CountryTwName: "甘比亞", CountryEnName: "The Gambia" ),
    country( CurrencyCode: "GNF", CountryTwName: "幾內亞", CountryEnName: "Guinea" ),
    country( CurrencyCode: "GTQ", CountryTwName: "瓜地馬拉", CountryEnName: "Guatemala" ),
    country( CurrencyCode: "GYD", CountryTwName: "蓋亞那", CountryEnName: "Guyana" ),
    country( CurrencyCode: "HKD", CountryTwName: "香港", CountryEnName: "Hong Kong" ),
    country( CurrencyCode: "HNL", CountryTwName: "宏都拉斯", CountryEnName: "Honduras" ),
    country( CurrencyCode: "HRK", CountryTwName: "克羅埃西亞", CountryEnName: "Croatia" ),
    country( CurrencyCode: "HTG", CountryTwName: "海地", CountryEnName: "Haiti" ),
    country( CurrencyCode: "HUF", CountryTwName: "匈牙利", CountryEnName: "Hungary" ),
    country( CurrencyCode: "IDR", CountryTwName: "印尼", CountryEnName: "Indonesia" ),
    country( CurrencyCode: "ILS", CountryTwName: "以色列", CountryEnName: "Israel" ),
    country( CurrencyCode: "IMP", CountryTwName: "曼島", CountryEnName: "Isle of Man" ),
    country( CurrencyCode: "INR", CountryTwName: "印度", CountryEnName: "India" ),
    country( CurrencyCode: "IQD", CountryTwName: "伊拉克", CountryEnName: "Iraq" ),
    country( CurrencyCode: "IRR", CountryTwName: "伊朗", CountryEnName: "Iran" ),
    country( CurrencyCode: "ISK", CountryTwName: "冰島", CountryEnName: "Iceland" ),
    country( CurrencyCode: "JEP", CountryTwName: "澤西", CountryEnName: "Jersey" ),
    country( CurrencyCode: "JMD", CountryTwName: "牙買加", CountryEnName: "Jamaica" ),
    country( CurrencyCode: "JOD", CountryTwName: "約旦", CountryEnName: "Jordan" ),
    country( CurrencyCode: "JPY", CountryTwName: "日本", CountryEnName: "Japan" ),
    country( CurrencyCode: "KES", CountryTwName: "肯亞", CountryEnName: "Kenya" ),
    country( CurrencyCode: "KGS", CountryTwName: "吉爾吉斯", CountryEnName: "Kyrgyzstan" ),
    country( CurrencyCode: "KHR", CountryTwName: "柬埔寨", CountryEnName: "Cambodia" ),
    country( CurrencyCode: "KID", CountryTwName: "吉里巴斯", CountryEnName: "Kiribati" ),
    country( CurrencyCode: "KMF", CountryTwName: "葛摩", CountryEnName: "Comoros" ),
    country( CurrencyCode: "KRW", CountryTwName: "南韓", CountryEnName: "South Korea" ),
    country( CurrencyCode: "KWD", CountryTwName: "科威特", CountryEnName: "Kuwait" ),
    country( CurrencyCode: "KYD", CountryTwName: "開曼群島", CountryEnName: "Cayman Islands" ),
    country( CurrencyCode: "KZT", CountryTwName: "哈薩克", CountryEnName: "Kazakhstan" ),
    country( CurrencyCode: "LAK", CountryTwName: "寮國", CountryEnName: "Laos" ),
    country( CurrencyCode: "LBP", CountryTwName: "黎巴嫩", CountryEnName: "Lebanon" ),
    country( CurrencyCode: "LKR", CountryTwName: "斯里蘭卡", CountryEnName: "Sri Lanka" ),
    country( CurrencyCode: "LRD", CountryTwName: "賴比瑞亞", CountryEnName: "Liberia" ),
    country( CurrencyCode: "LSL", CountryTwName: "賴索托", CountryEnName: "Lesotho" ),
    country( CurrencyCode: "LYD", CountryTwName: "利比亞", CountryEnName: "Libya" ),
    country( CurrencyCode: "MAD", CountryTwName: "摩洛哥", CountryEnName: "Morocco" ),
    country( CurrencyCode: "MDL", CountryTwName: "摩爾多瓦", CountryEnName: "Moldova" ),
    country( CurrencyCode: "MGA", CountryTwName: "馬達加斯加", CountryEnName: "Madagascar" ),
    country( CurrencyCode: "MKD", CountryTwName: "北馬其頓", CountryEnName: "North Macedonia" ),
    country( CurrencyCode: "MMK", CountryTwName: "緬甸", CountryEnName: "Myanmar" ),
    country( CurrencyCode: "MNT", CountryTwName: "蒙古", CountryEnName: "Mongolia" ),
    country( CurrencyCode: "MOP", CountryTwName: "澳門", CountryEnName: "Macau" ),
    country( CurrencyCode: "MRU", CountryTwName: "茅利塔尼亞", CountryEnName: "Mauritania" ),
    country( CurrencyCode: "MUR", CountryTwName: "模里西斯", CountryEnName: "Mauritius" ),
    country( CurrencyCode: "MVR", CountryTwName: "馬爾地夫", CountryEnName: "Maldives" ),
    country( CurrencyCode: "MWK", CountryTwName: "馬拉威 ", CountryEnName: "Malawi" ),
    country( CurrencyCode: "MXN", CountryTwName: "墨西哥", CountryEnName: "Mexico" ),
    country( CurrencyCode: "MYR", CountryTwName: "馬來西亞", CountryEnName: "Malaysia" ),
    country( CurrencyCode: "MZN", CountryTwName: "莫三比克", CountryEnName: "Mozambique" ),
    country( CurrencyCode: "NAD", CountryTwName: "納米比亞", CountryEnName: "Namibia" ),
    country( CurrencyCode: "NGN", CountryTwName: "奈及利亞", CountryEnName: "Nigeria" ),
    country( CurrencyCode: "NIO", CountryTwName: "尼加拉瓜", CountryEnName: "Nicaragua" ),
    country( CurrencyCode: "NOK", CountryTwName: "挪威", CountryEnName: "Norway" ),
    country( CurrencyCode: "NPR", CountryTwName: "尼泊爾", CountryEnName: "Nepal" ),
    country( CurrencyCode: "NZD", CountryTwName: "紐西蘭", CountryEnName: "New Zealand" ),
    country( CurrencyCode: "OMR", CountryTwName: "阿曼", CountryEnName: "Oman" ),
    country( CurrencyCode: "PAB", CountryTwName: "巴拿馬", CountryEnName: "Panama" ),
    country( CurrencyCode: "PEN", CountryTwName: "秘魯", CountryEnName: "Peru" ),
    country( CurrencyCode: "PGK", CountryTwName: "巴布亞紐幾內亞", CountryEnName: "Papua New Guinea" ),
    country( CurrencyCode: "PHP", CountryTwName: "菲律賓", CountryEnName: "Philippines" ),
    country( CurrencyCode: "PKR", CountryTwName: "巴基斯坦", CountryEnName: "Pakistan" ),
    country( CurrencyCode: "PLN", CountryTwName: "波蘭", CountryEnName: "Poland" ),
    country( CurrencyCode: "PYG", CountryTwName: "巴拉圭", CountryEnName: "Paraguay" ),
    country( CurrencyCode: "QAR", CountryTwName: "卡達", CountryEnName: "Qatar" ),
    country( CurrencyCode: "RON", CountryTwName: "羅馬尼亞", CountryEnName: "Romania" ),
    country( CurrencyCode: "RSD", CountryTwName: "塞爾維亞", CountryEnName: "Serbia" ),
    country( CurrencyCode: "RUB", CountryTwName: "俄羅斯", CountryEnName: "Russia" ),
    country( CurrencyCode: "RWF", CountryTwName: "盧安達", CountryEnName: "Rwanda" ),
    country( CurrencyCode: "SAR", CountryTwName: "沙烏地阿拉伯", CountryEnName: "Saudi Arabia" ),
    country( CurrencyCode: "SBD", CountryTwName: "索羅門", CountryEnName: "Solomon Islands" ),
    country( CurrencyCode: "SCR", CountryTwName: "塞席爾", CountryEnName: "Seychelles" ),
    country( CurrencyCode: "SDG", CountryTwName: "蘇丹", CountryEnName: "Sudan" ),
    country( CurrencyCode: "SEK", CountryTwName: "瑞典", CountryEnName: "Sweden" ),
    country( CurrencyCode: "SGD", CountryTwName: "新加坡", CountryEnName: "Singapore" ),
    country( CurrencyCode: "SHP", CountryTwName: "聖赫勒拿", CountryEnName: "Saint Helena" ),
    country( CurrencyCode: "SLE", CountryTwName: "獅子山", CountryEnName: "Sierra Leone" ),
    country( CurrencyCode: "SOS", CountryTwName: "索馬利亞", CountryEnName: "Somalia" ),
    country( CurrencyCode: "SRD", CountryTwName: "蘇利南", CountryEnName: "Suriname" ),
    country( CurrencyCode: "SSP", CountryTwName: "南蘇丹", CountryEnName: "South Sudan" ),
    country( CurrencyCode: "STN", CountryTwName: "聖多美", CountryEnName: "São Tomé and Príncipe" ),
    country( CurrencyCode: "SYP", CountryTwName: "敘利亞", CountryEnName: "Syria" ),
    country( CurrencyCode: "SZL", CountryTwName: "史瓦帝尼", CountryEnName: "Eswatini" ),
    country( CurrencyCode: "THB", CountryTwName: "泰國", CountryEnName: "Thailand" ),
    country( CurrencyCode: "TJS", CountryTwName: "塔吉克", CountryEnName: "Tajikistan" ),
    country( CurrencyCode: "TMT", CountryTwName: "土庫曼", CountryEnName: "Turkmenistan" ),
    country( CurrencyCode: "TND", CountryTwName: "突尼西亞", CountryEnName: "Tunisia" ),
    country( CurrencyCode: "TOP", CountryTwName: "東加", CountryEnName: "Tonga" ),
    country( CurrencyCode: "TRY", CountryTwName: "土耳其", CountryEnName: "Turkey" ),
    country( CurrencyCode: "TTD", CountryTwName: "千里達", CountryEnName: "Trinidad and Tobago" ),
    country( CurrencyCode: "TVD", CountryTwName: "吐瓦魯", CountryEnName: "Tuvalu" ),
    country( CurrencyCode: "TWD", CountryTwName: "中華民國", CountryEnName: "Taiwan" ),
    country( CurrencyCode: "TZS", CountryTwName: "坦尚尼亞", CountryEnName: "Tanzania" ),
    country( CurrencyCode: "UAH", CountryTwName: "烏克蘭", CountryEnName: "Ukraine" ),
    country( CurrencyCode: "UGX", CountryTwName: "烏干達", CountryEnName: "Uganda" ),
    country( CurrencyCode: "USD", CountryTwName: "美國", CountryEnName: "United States" ),
    country( CurrencyCode: "UYU", CountryTwName: "烏拉圭", CountryEnName: "Uruguay" ),
    country( CurrencyCode: "UZS", CountryTwName: "烏茲別克", CountryEnName: "Uzbekistan" ),
    country( CurrencyCode: "VES", CountryTwName: "委內瑞拉", CountryEnName: "Venezuela" ),
    country( CurrencyCode: "VND", CountryTwName: "越南", CountryEnName: "Vietnam" ),
    country( CurrencyCode: "VUV", CountryTwName: "萬那杜", CountryEnName: "Vanuatu" ),
    country( CurrencyCode: "WST", CountryTwName: "薩摩亞", CountryEnName: "Samoa" ),
    country( CurrencyCode: "XAF", CountryTwName: "中部非洲經濟與貨幣共同體", CountryEnName: "CEMAC" ),
    country( CurrencyCode: "XCD", CountryTwName: "東加勒比國家組織", CountryEnName: "Organisation of Eastern Caribbean States" ),
    country( CurrencyCode: "XDR", CountryTwName: "國際貨幣基金組織", CountryEnName: "International Monetary Fund" ),
    country( CurrencyCode: "XPF", CountryTwName: "法國海外部分", CountryEnName: "Collectivités d'Outre-Mer" ),
    country( CurrencyCode: "YER", CountryTwName: "葉門", CountryEnName: "Yemen" ),
    country( CurrencyCode: "ZAR", CountryTwName: "南非", CountryEnName: "South Africa" ),
    country( CurrencyCode: "ZMW", CountryTwName: "尚比亞", CountryEnName: "Zambia" ),
    country( CurrencyCode: "ZWL", CountryTwName: "辛巴威", CountryEnName: "Zimbabwe" )
]
